### ISSUE TITLE
Can't log in on beta.chalmers.it

### ISSUE THREAD

**Issue by SamuelHakansson** [cthit/chalmersit-rails#101]
Clicked prefilled login as well as "remember me", got to the error page, afterwards when clicking "login", I instantly see the same error page.
![image](https://cloud.githubusercontent.com/assets/9130916/20259289/6cfb0ef2-aa54-11e6-99b9-e8a30a900323.png)

**Comment by Vilddjur** [comment]
This is since b72ac5d251cc5ec7b8c128dc151144d34c15440e

**Comment by lindskogen** [comment]
See my comment on #102

**Comment by Vilddjur** [comment]
It works when I move
`   
  get '*path' => 'pages#show'
`
to the bottom

**Comment by Vilddjur** [comment]
solved as of 2f708c403d6f20b38cb97800c4a3943f7168356b
