### ISSUE TITLE
Getting page not found when logging in/logging out.

### ISSUE THREAD

**Issue by Vilddjur** [cthit/chalmersit-rails#102]
Since b72ac5d251cc5ec7b8c128dc151144d34c15440e you are unable to login.
![image](https://i.gyazo.com/85901859ec9ce63fae37d60252d88f95.png)

**Comment by Vilddjur** [comment]
duplicate of #101

**Comment by lindskogen** [comment]
I probably screwed up the priority of routes. Move everything below the locale block on top of it
