### ISSUE TITLE
Page "navigation indicator" not working correctly in production

### ISSUE THREAD

**Issue by Vilddjur** [cthit/chalmersit-rails#109]
The indicator works only on swedish in production, I was not able to replicate this locally.
Expected behaviour: When on the page [The Division](https://beta.chalmers.it/pages) the menu link should be highlighted, in both english and swedish.
Actual behaviour: The menu link is only highlighted for the swedish locale
![image](https://i.gyazo.com/0cb4f5326e2f3bbc687d6844b4273b7f.png)
![image](https://i.gyazo.com/aca777ae096bfb4a1ca22dbe180f1a53.png)

**Comment by Vilddjur** [comment]
![image](https://i.gyazo.com/46fa20190aa7c47639375238a60a64ca.png)
Seems like the issue is also there when in a different page. The indicator should be on "Kurser" but is still on Sektionen.

**Comment by lindskogen** [comment]
Check out:
app/helpers/application_helper.rb:header_link_to_current
Is the path different from request.fullpath?

**Comment by Kalior** [comment]
Does not work for any locale in production for me. Might be a caching problem?
https://github.com/cthit/chalmersit-rails/blob/develop/app/views/layouts/_header.html.erb#L39-L43

**Comment by lindskogen** [comment]
wow... @Kalior, you're totally right, remove the caching block :)

**Comment by lindskogen** [comment]
Would be nice if we could find som way to not hit the database on every page refresh though :)

**Comment by Kalior** [comment]
How about caching the menu links and then running header_link_to_current every page refresh? Like so:
```
<% cache ['main-menu', I18n.locale] do %>
  <% @menu_links = Menu.where(name: 'main').last.links %>
<% end %>
<% @menu_links.each do |link| %>
  <%= header_link_to_current t(link.title), link.path %>
<% end %>
```

**Comment by lindskogen** [comment]
The `cache` block only captures output though, so the assignment wouldn't work. Let me try something

**Comment by Kalior** [comment]
Ah okay, caching is confusing :no_mouth:
