### ISSUE TITLE
Update header image

### ISSUE THREAD

**Issue by Dr-Horv** [cthit/chalmersit-rails#111]
The current header-image on beta.chalmers.it is not up to date and should be replaced

**Comment by Vilddjur** [comment]
sort of duplicate #10

**Comment by Dr-Horv** [comment]
Well it depends, if random image is implemented before launch. I'd say the random image is a nice-to-heave feature while updating the current is a must before launch.

**Comment by Vilddjur** [comment]
fixed asof 36053886024747b1e424ed500fcffd08d26294bd
