### ISSUE TITLE
Printing with no file gives rails error

### ISSUE THREAD

**Issue by Kalior** [cthit/chalmersit-rails#112]
If I try to print without specifying a file, I receive a rails error

Testing locally gives the error:
`no implicit conversion of nil into String`
in `app/models/print.rb`
```   
def mime_type(file)
      `file --mime-type -b '#{File.absolute_path(file)}'`.
end
```

Would be nice if this was caught in the front end.

**Comment by lindskogen** [comment]
We could add a `presence` validation to the file field in the print job model?

**Comment by Kalior** [comment]
the model for print jobs already have 
`validates :file, presence: true, unless: 'file_cache.present?'` 
so there must be something with the `file_cache` that's wrong.
