### ISSUE TITLE
Pages route should not show a list of pages

### ISSUE THREAD

**Issue by Kalior** [cthit/chalmersit-rails#114]
Should instead contain some information about the student division.

Compare [https://chalmers.it/sektionen/](https://chalmers.it/sektionen/) and [https://beta.chalmers.it/pages](https://beta.chalmers.it/pages)

**Comment by lindskogen** [comment]
I think the idea was to create a "sektionen"-page with children and link to that. 
This will make the URL look like it does today

**Comment by Kalior** [comment]
So the route for pages will go to a specific page, specified in the code? Am I understanding this correctly?

**Comment by Vilddjur** [comment]
I guess we can just have a page in seed.rb?

**Comment by Kalior** [comment]
Yeah that would work.
