### ISSUE TITLE
Pages can be children to pages they are parents to

### ISSUE THREAD

**Issue by Kalior** [cthit/chalmersit-rails#124]
This creates a circular relation, which is a problem.

**Comment by lindskogen** [comment]
Are you sure? 
https://github.com/cthit/chalmersit-rails/blob/develop/app/models/page.rb#L19

**Comment by Kalior** [comment]
Well, I was able to create a page with two children and then set one of those children to be the page's parent. I agree that the code seems to prevent this. Can you try to reproduce?

**Comment by lindskogen** [comment]
Is that really an issue though? What you did was just moving it to the top of the hierarchy? Where is the circular relation?

**Comment by Kalior** [comment]
Well then the original page has a child that has a child that is the original page. Then I got a "Stack too deep" error from rails.

**Comment by lindskogen** [comment]
Sounds broken, will check!
