### ISSUE TITLE
When uploading a file, the tab with the language not selected gets the same text as the one currently active

### ISSUE THREAD

**Issue by NeonNeon** [cthit/chalmersit-rails#140]
If I write "English" in the English tab and "Swedish" in the swedish tab. Then I upload a file in the Swedish tab both tabs will contain the text "Swedish + link_to_file"

**Comment by Vilddjur** [comment]
so the english tab now contains:
"EnglishSwedish + link"?

**Comment by NeonNeon** [comment]
No, the original text gets over written which is a big problem if I have forgotten to upload some file when I start writing my post.

**Comment by Vilddjur** [comment]
Oh I see, I'll look into it
