### ISSUE TITLE
There is a link to update news posts even when one is signed out, but only when the language is set to english.

### ISSUE THREAD

**Issue by NeonNeon** [cthit/chalmersit-rails#141]
![image](https://cloud.githubusercontent.com/assets/6126906/20560867/c7ae23ba-b17b-11e6-90a9-df1252028226.png)
See down to the left.

**Comment by NeonNeon** [comment]
The link gladly does not work.

**Comment by Vilddjur** [comment]
This is really weird since both have the same logic for hiding it 
https://github.com/cthit/chalmersit-rails/blob/develop/app/views/posts/_post.html.erb#L15

**Comment by Kerp1** [comment]
When I tried to reproduce this on my machine it worked as expected. The problem seems to only exist on the live page.

**Comment by Vilddjur** [comment]
Cacheing? Cacheing.

**Comment by Vilddjur** [comment]
@lindskogen what about changing 
`<% cache ['home_posts', I18n.locale, @posts.first] do  %>`
to 
`<% cache ['home_posts', I18n.locale, @posts.first+current_user] do  %>` ?
in https://github.com/cthit/chalmersit-rails/blob/develop/app/views/home/index.html.erb#L1
I guess we would have to change 
`<% cache ['home', I18n.locale, post] do %>`
to 
`<% cache ['home', I18n.locale, post+current_user] do %>`
aswell. 
The issue with this it would create so much cache :confused:

**Comment by Vilddjur** [comment]
The dream solution would be to have a ignored cache block or something like that

**Comment by lindskogen** [comment]
@Vilddjur: What about using cache for users who are not signed in?
Instead use `cache [current_user.present?]`

**Comment by Vilddjur** [comment]
I mean the content will be different between each user aswell as logged in users and not logged in users. I thought that current_user would be validated as nil so that wouldn't be an issue?

**Comment by lindskogen** [comment]
This is what we need! [`cache_unless`](http://apidock.com/rails/v4.2.7/ActionView/Helpers/CacheHelper/cache_unless)

    cache_unless current_user.present?, ['home_posts', I18n.locale, @posts.first] do

**Comment by Vilddjur** [comment]
closed by 00f878ff941ecc005f723096f76bb109b15e426f
