### ISSUE TITLE
Kårkort menu link is not correct

### ISSUE THREAD

**Issue by Kalior** [cthit/chalmersit-rails#146]
Takes you to kårkort.se where a https error and a
```
Potential DNS Rebind attack detected, see http://en.wikipedia.org/wiki/DNS_rebinding
Try accessing the router by IP address instead of by hostname.
```
error message is displayed.

**Comment by Vilddjur** [comment]
Works for me, but I'm redirected to http://kortladdning3.chalmerskonferens.se/

**Comment by Kalior** [comment]
Right, I was on the digIT network. That might be the problem...

**Comment by Vilddjur** [comment]
That can be the issue yes. Can you check and if so close the issue please?

**Comment by Kalior** [comment]
I switched to eduroam and now I get digITs obi wan page. `not the site you're looking for`

**Comment by lindskogen** [comment]
Issue is with https :(
