### ISSUE TITLE
Keep original filename when uploading content

### ISSUE THREAD

**Issue by NeonNeon** [cthit/chalmersit-rails#150]
Right now each time one uploads a file it gets a hashed filenamne (like XaKsoskax.pdf) however since the original filename is removed completely some information is lost. For example if I upload all reports from the different committees for the student division meeting I need to keep track of which hashed file name is what committee's report. Or if we are to move all documents from [sektionen/dokument](https://chalmers.it/sektionen/dokument) it would be nice if their filenames were understandable.

I guess we hash the filenames to avoid collisions and that's probably a good feature but I propose a change

- We use original filenames when possible (so when someone uploads a file the site checks if that filename is in use already, and if it is it does like in Windows and just add some number on the end of the filename like "verksamhetsrapport (1).pdf" if "verksamhetsrapport.pdf" already exists.
- OR we always append a hash to each file but we keep the original filenamne as a suffix, in this way we should always avoid collisions, the above example would become "verksamhetsrapport_XaKsoskax.pdf"

**Comment by lindskogen** [comment]
The hash is unnecessary at this point. Remove it entirely, or make it depend on the current time etc. (and put it on the end)

**Comment by Vilddjur** [comment]
It currently depends on the time? https://github.com/cthit/chalmersit-rails/blob/develop/app/uploaders/article_image_uploader.rb#L49

**Comment by Vilddjur** [comment]
closed by 3b3bf5d61ee9ab26d53611aba10c4da850967101

**Comment by lindskogen** [comment]
Current solution removes file extension?

**Comment by Vilddjur** [comment]
No it should not https://github.com/cthit/chalmersit-rails/blob/develop/app/uploaders/article_image_uploader.rb#L49
 is last and that line includes `File.extname(filename)` at least it didn't do so locally
