### ISSUE TITLE
Post policy seems to be incorrect

### ISSUE THREAD

**Issue by Vilddjur** [cthit/chalmersit-rails#152]
From what it seems like is as long as you are in a group you are able to edit all posts, confirm @Kalior?

**Comment by Kalior** [comment]
At the very least, you can view the edit page. I haven't tried actually editing a post.

**Comment by Vilddjur** [comment]
hmm, yea I only tried doing it not logged in.. I might have a fix

**Comment by Vilddjur** [comment]
f8be0f9db68d449a6614e9492dd5549873247102 this did not fix it :confused:

**Comment by lindskogen** [comment]
@Vilddjur PostPolicy inherits from ApplicationPolicy, in which `edit?` already is the same as `update?`. Maybe we should write some tests! https://github.com/elabs/pundit#rspec

**Comment by Vilddjur** [comment]
Sounds like a good idea! :dancer:

**Comment by Vilddjur** [comment]
closed asof pull #160
