### ISSUE TITLE
Confusing buttons

### ISSUE THREAD

**Issue by oherik** [cthit/chalmersit-rails#157]
After two years on IT, I still occasionally press the wrong button when I want to book a group room. This is because I just see "Booking" and press it, but that leads to a page for booking Hubben. I suggest to differentiate the two buttons "Booking" and "Group room" more, perhaps by using different titles or different images.

**Comment by lindskogen** [comment]
old:
![image](https://cloud.githubusercontent.com/assets/817046/20745019/7e55c0ba-b6df-11e6-9e6c-d6570ded08bc.png)

vs new:
![image](https://cloud.githubusercontent.com/assets/817046/20745009/6c5c258e-b6df-11e6-8313-ee423f90e417.png)

**Comment by Kalior** [comment]
@oherik do you consider the new design confusing as well?

**Comment by oherik** [comment]
Honestly, yes. I made the same mistake a couple of days ago using
beta.chalmers.it

2016-12-02 15:31 GMT+01:00 Joel <notifications@github.com>:

**Comment by jesperlindstrom** [comment]
Perhaps rename the "Booking" text to "bookIT" or "Internal booking" or something along that line? I mean, it's mainly committees that uses the link anyway, so if it says bookIT that should be clear enough.

**Comment by Kalior** [comment]
@jesperlindstrom check #163
