### ISSUE TITLE
Tooltip on quick shortcuts is weirdly positioned

### ISSUE THREAD

**Issue by johanbrook** [cthit/chalmersit-rails#167]
On frontpage, Safari. Seems isolated to here?

<img width="328" alt="skarmavbild 2016-12-06 kl 15 48 42" src="https://cloud.githubusercontent.com/assets/437261/20942922/895b0d6c-bbcb-11e6-93ac-7d13f80d1400.png">

**Comment by lindskogen** [comment]
This is apparently by design: http://foundation.zurb.com/sites/docs/v/5.5.3/components/tooltips.html

**Comment by johanbrook** [comment]
Oh. Possible to manually nudge them from the markup (in an attribute or something) to position the arrow on the center of the icon?

**Comment by lindskogen** [comment]
Thinking about upgrading to foundation 6 for this
