### ISSUE TITLE
Search, sign in, and language switcher can be beautified

### ISSUE THREAD

**Issue by johanbrook** [cthit/chalmersit-rails#168]
These guys look a bit box-y 🎇 

<img width="427" alt="skarmavbild 2016-12-06 kl 15 49 51" src="https://cloud.githubusercontent.com/assets/437261/20942956/ab4f186e-bbcb-11e6-9ffe-01cde6c3dfec.png">

**Comment by johanbrook** [comment]
#wontfix ? :D

**Comment by jesperlindstrom** [comment]
Fixed as of PR #225 :)
