### ISSUE TITLE
Unclear authorization message when logging in

### ISSUE THREAD

**Issue by Meddan** [cthit/chalmersit-rails#173]
<img width="595" alt="screen shot 2016-12-07 at 09 46 42" src="https://cloud.githubusercontent.com/assets/3900604/20960746/29e66ea2-bc62-11e6-8b88-976f78207a45.png">

Only happens on first login.

**Comment by Vilddjur** [comment]
This is should be an issue on chamersit-account-rails

**Comment by Vilddjur** [comment]
Created new issue https://github.com/cthit/chalmersit-account-rails/issues/64
