### ISSUE TITLE
"Events today" shows event that occurs tomorrow

### ISSUE THREAD

**Issue by Kerp1** [cthit/chalmersit-rails#175]
It is currently december 7th and an even that is happening tomorrow is displayed in the "events today" box.

![2016-12-07-104132_724x172_scrot](https://cloud.githubusercontent.com/assets/4082428/20962519/e9371f34-bc69-11e6-9fb8-4b5fa332ce8f.png)

**Comment by Kalior** [comment]
I believe this is to mimic the behaviour on old chalmers.it, we just never changed the label?

**Comment by Kalior** [comment]
Do we want to show the next event as it was in old chalmers.it or events today as the label reads?

**Comment by lindskogen** [comment]
Most likely upcoming events
