### ISSUE TITLE
Language isn't sticking

### ISSUE THREAD

**Issue by abjugard** [cthit/chalmersit-rails#179]
When visiting chalmers.it I keep having to manually select swedish every time. As 99% of the visitors are swedish this seems like a pretty inconvenient solution.

![screen recording 2016-12-07 at 11 22 am](https://cloud.githubusercontent.com/assets/287697/20963912/b4829894-bc6f-11e6-954e-171da90ae2eb.gif)

My language is set to Swedish in the profile settings as well.

![screen shot 2016-12-07 at 11 27 44](https://cloud.githubusercontent.com/assets/287697/20964039/387d23e4-bc70-11e6-8717-f2c97ae56d44.png)

**Comment by Vilddjur** [comment]
closed by a54c8b1a5b03f8e57cea669ec9e2d2703c0bbc7d
