### ISSUE TITLE
Course list is broken on mobile

### ISSUE THREAD

**Issue by jesperlindstrom** [cthit/chalmersit-rails#182]
Course list is broken on smaller screens. We should really try not to use tables as they can't be adapted for mobile in any good way.

<img width="385" alt="skarmavbild 2016-12-07 kl 12 28 03" src="https://cloud.githubusercontent.com/assets/1730738/20966045/cc903b22-bc78-11e6-98ba-1d6fff829138.png">

**Comment by lindskogen** [comment]
Suggestion; remove course page and link to wikit

**Comment by Vilddjur** [comment]
The main issue with that is that we want non IT people to have access to the course list. For example newly accepted students that want to check the courses during the summer.

**Comment by Vilddjur** [comment]
closed by dafb41f29430828d23d5c7349c3000df1fdff113
