### ISSUE TITLE
Add course contains weird list of study periods

### ISSUE THREAD

**Issue by jesperlindstrom** [cthit/chalmersit-rails#183]
<img width="658" alt="skarmavbild 2016-12-07 kl 12 28 19" src="https://cloud.githubusercontent.com/assets/1730738/20966080/f92f3d36-bc78-11e6-9857-9cceac2e8f2c.png">

**Comment by Kalior** [comment]
This is due to the database containing that amount of Periods. There should only be one of each period in the database. Probably due to too many seeds, as seeds.rb creates a Period 1,2,3,4.

**Comment by lindskogen** [comment]
Suggestion; remove course page and link to wikit
