### ISSUE TITLE
Back button on pages is hard to find and unintuitive

### ISSUE THREAD

**Issue by jesperlindstrom** [cthit/chalmersit-rails#184]
# The problem
Back button is hard to find and it's not very obvious where it's supposed to take me – does it take me back to the previous page? Nope, it takes me to the "list" page for the page type, which isn't necessarily what "back" means at all times (i.e. if I don't come directly from the list page).
<img width="133" alt="skarmavbild 2016-12-07 kl 12 31 42" src="https://cloud.githubusercontent.com/assets/1730738/20966117/293daa9e-bc79-11e6-9464-233d13442800.png">

# Proposed solution:
Breadcrumbs, on all page types where back button is. **Pros:** common pattern which people are used to. More obvious where it's supposed to go when I click on the link. Also easier to find since they're on the top.
<img width="394" alt="skarmavbild 2016-12-07 kl 12 33 23" src="https://cloud.githubusercontent.com/assets/1730738/20966226/8d2eef90-bc79-11e6-8727-c448d9d82b1c.png">

**Comment by Kalior** [comment]
I think we can just remove all the back links instead? I can't think of any page where they actually add anything.
