### ISSUE TITLE
Clarify the "Program" field on "Create course"

### ISSUE THREAD

**Issue by jesperlindstrom** [cthit/chalmersit-rails#185]
UX issue on the create course page. Hard to understand what to enter into the "program" field. I assume it's the program the course belongs to... should it be a dropdown? Or at the very least an explanation should be added next to the field.
<img width="377" alt="skarmavbild 2016-12-07 kl 12 38 18" src="https://cloud.githubusercontent.com/assets/1730738/20966338/12387152-bc7a-11e6-98f4-b03276a1dd4c.png">

**Comment by lindskogen** [comment]
Suggestion; remove course page and link to wikit
