### ISSUE TITLE
Committees should be able to edit and create pages

### ISSUE THREAD

**Issue by jesperlindstrom** [cthit/chalmersit-rails#190]
At the very least, armIT should be allowed to edit the "company" pages, and styrIT should be allowed to edit the section and document pages.

**Comment by Kalior** [comment]
This sounds complicated, creating owners of specific pages... Do we want to do that in the way it is done in posts or do we simply allow armIT, styrIT, snIT to edit pages?

**Comment by lindskogen** [comment]
Probably just set those 3 to be "page-admins"

**Comment by Vilddjur** [comment]
I agree. I think that will cover the main problems and wont be very hard to implement
