### ISSUE TITLE
Links in "Om sektionen" strips locale variable

### ISSUE THREAD

**Issue by lindskogen** [cthit/chalmersit-rails#191]
![image](https://cloud.githubusercontent.com/assets/817046/20976957/6d068f72-bca4-11e6-8ccb-654e66ec3145.png)

**Comment by Kalior** [comment]
Seems to strip only the default locale?

**Comment by Vilddjur** [comment]
I dont think this is an issue? The swedish body/title and the engilish is the same atm.

**Comment by lindskogen** [comment]
Well, no issue except the entire page changes language.

**Comment by Vilddjur** [comment]
I am not sure what you mean, the page has the correct language for me, except ofc the body of the page.
