### ISSUE TITLE
Some sort of delayed redirect upon leaving the site

### ISSUE THREAD

**Issue by Kalior** [cthit/chalmersit-rails#194]
All the links on the site that leads away from it (e.g timeedit, bookit, findit, courses) should have some sort of delayed redirect. Maybe a popup that explains you are about to leave the site so you can cancel if you want to or something like that. Thoughts?

**Comment by lindskogen** [comment]
Or an icon, something like this?

![image](https://cloud.githubusercontent.com/assets/817046/21015092/e7b71bbc-bd60-11e6-98b1-35fcd6ad0380.png)

**Comment by Kalior** [comment]
fixed as of 5557e61
