### ISSUE TITLE
Menu, MenuLinks, Committees index pages should be hidden from regular users

### ISSUE THREAD

**Issue by Kalior** [cthit/chalmersit-rails#208]
It seems anyone can enter the following pages (and maybe edit the menu_links??). This should obviously be prevented.
https://chalmers.it/menu_links
https://chalmers.it/menus
https://chalmers.it/committees
We should hide menu and menu_link, but maybe committees can redirect to pages instead, or to the show view with styrit or something. 

I also find it slightly hilarious how many menus and menu_links there are 🗡

**Comment by lindskogen** [comment]
`rake db:seed` every time!
