### ISSUE TITLE
Improve design of paginate

### ISSUE THREAD

**Issue by Kalior** [cthit/chalmersit-rails#213]
There are some translations missing, and I feel like we could improve how this looks in some further way. No concrete idea, though, maybe @jesperlindstrom has some thoughts?

![image](https://cloud.githubusercontent.com/assets/2412457/21076498/38e15cf0-bf2d-11e6-9f8b-99fa21e59aed.png)

**Comment by jesperlindstrom** [comment]
![skarmavbild 2016-12-11 kl 12 25 19](https://cloud.githubusercontent.com/assets/1730738/21079788/ed6eb48c-bf9c-11e6-9ab1-cf7406a92f72.png)

Something like this mockup would be enough. The primary use case is to go to the next page, so I really don't think we need to list 12 different pages, could get by with just a couple and then use the prev/next buttons.

**Comment by lindskogen** [comment]
https://github.com/mislav/will_paginate/wiki/API-documentation#will_paginatecollection-options
`inner_window` seems to be what we need:

`will_paginate @pages, inner_window: 4`

**Comment by lindskogen** [comment]
It seems that we need to provide [`I18n`](https://github.com/mislav/will_paginate/wiki/I18n) for Swedish as they look like this in English:
![image](https://cloud.githubusercontent.com/assets/817046/21079837/7c879822-bf9e-11e6-8dd4-d08efbed071e.png)

`Page Gap` should be localized to '...'
