### ISSUE TITLE
Show committee members on committee pages

### ISSUE THREAD

**Issue by jesperlindstrom** [cthit/chalmersit-rails#216]
We've received requests to list the committee members on the committee pages, just like on the old site. Could this be implemented via the group system perhaps by simply looping out all members for the committee?

**Comment by Kalior** [comment]
I suppose we can cache the users in each committee (by going through all users and checking which are members), but I think it's cleaner if we can request the users from account, for example by adding it to the json for a group and requestion from https://beta-account.chalmers.it/groups/digit15.json. @Vilddjur Is this possible to implement? Adding a users field with an array of cids to the json for example? Can we also add an description per user to groups in accounts?

**Comment by Vilddjur** [comment]
Yea I think it wouldnt be too much of a hassle.
