### ISSUE TITLE
Add option/hint in cheat sheet on how to center images in posts.

### ISSUE THREAD

**Issue by NeonNeon** [cthit/chalmersit-rails#243]
Almost all posts have left-aligned images and I think it's because no body knows how to actually center an image. One can just include a bit of markup:
![image](https://cloud.githubusercontent.com/assets/6126906/23123360/549b58b0-f768-11e6-8eed-9c39ec5ae184.png)

**Comment by lindskogen** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p

> **Note**: The align attribute on &lt;p&gt; tags is obsolete and should no longer be used.

**Comment by NeonNeon** [comment]
Whatever works
