### ISSUE TITLE
Upgrade to Rails 5

### ISSUE THREAD

**Issue by lindskogen** [cthit/chalmersit-rails#244]
Currently depending on https://github.com/globalize/globalize to release a `rails >= 5` compatible version

**Comment by malmers** [comment]
When globalized is ready for rails 5, update dependencies with:

bundle update rails factory_girl_rails jquery-rails coffee-rails jquery-fileupload-rails font-awesome-rails momentjs-rails rspec-rails simple_form globalize

**Comment by Vilddjur** [comment]
From what I can read from the github page for globalize it should be ready for Rails 5
'You have to use branch master to work with Rails 5.'

**Comment by lindskogen** [comment]
Without looking into it, double check that the gem is released and published to rubygems first!

**Comment by Xiaoming94** [comment]
Right now, It looks like servers are going to ship with Openssl-1.1.0 which is incompatible with Ruby versions < 2.4 (as according to [This page](https://wiki.archlinux.org/index.php/RVM#RVM_uses_wrong_OpenSSL_version) and [rbenv's own wiki](https://github.com/rbenv/ruby-build/wiki)) Maybe we really shall consider doing a revision of Rails and Ruby versions, and determine a fix a soon as possible?

**Comment by Xiaoming94** [comment]
This is now fixed with #301 :)

**Comment by Xiaoming94** [comment]
Closing this now
