### ISSUE TITLE
Shouldn't be able to remove other peoples comments

### ISSUE THREAD

**Issue by Kalior** [cthit/chalmersit-rails#246]
I don't think I should be able to do this, but the option shows up as a link:
![image](https://cloud.githubusercontent.com/assets/2412457/23136241/1fa48364-f79c-11e6-8971-d29549ce1bc6.png)

**Comment by Vilddjur** [comment]
Cache most likely
https://github.com/cthit/chalmersit-rails/blob/develop/app/views/posts/show.html.erb#L14

**Comment by Kalior** [comment]
Just tried this out, and it was actually possible to remove the comment as well.

**Comment by Vilddjur** [comment]
closed as of 350a2203bc6c81db18a71f614ea1f6df26e01cb4
