### ISSUE TITLE
Newsmail that doesn't suck

### ISSUE THREAD

**Issue by lindskogen** [cthit/chalmersit-rails#3]
When post is created, make a delayed job using `after_create` to email the contents!

**Comment by Mxiim** [comment]
Mail sends directly after a newspost was created or updated.

**Comment by Edholm** [comment]
This should delegate to the notification service at account.chit

**Comment by Kalior** [comment]
@Mxiim status of this?

**Comment by Mxiim** [comment]
Closed by ad608d3
