### ISSUE TITLE
Printar alltid i färg

### ISSUE THREAD

**Issue by Oscmage** [cthit/chalmersit-rails#337]
Roligt nog träffade jag en student som använder chalmers.it varje gång för att skriva ut (Pluggar inte IT) och tydligen om man väljer en skrivare någon annanstans än vid E-studion så skrivs det automatiskt ut i färg.

**Comment by lindskogen** [comment]
För att klargöra lite, du menar att den skriver ut i färg på färgskrivare per default?

**Comment by Oscmage** [comment]
Enligt henne, ja.

**Comment by lindskogen** [comment]
Jag menar, det är ju typ en feature. Men jag antar att en bra lösning kanske är att skapa en färg/svartvitt-switch?

**Comment by Oscmage** [comment]
Det hade varit toppen! 👍
