### ISSUE TITLE
Document management

### ISSUE THREAD

**Issue by Edholm** [cthit/chalmersit-rails#34]
Preferably with support for cthit/document.

**Comment by NeonNeon** [comment]
This is an important issue since both snIT and StyrIT needs to upload the protocols of their meetings, it must be functional when the site goes live. 
It is also important that (pdf) files can be added to posts, for example sektionsmöteshandlingar etc

**Comment by Kalior** [comment]
I just had a thought regarding this. Is it reasonable that we should store these pdf documents on chalmers.it or should they rather be linked to from somewhere else? 

### Pros if placed somewhere else:
Documents can be accessed at all times even when this site is down, or when it gets replaced sometime in the future.

### Cons if placed somewhere else: 
Trickier to manage and no direct standard to follow as to where pdfs are placed.

**Comment by Vilddjur** [comment]
this is closed asof #63
