### ISSUE TITLE
Word cut off in post title

### ISSUE THREAD

**Issue by Hoidi** [cthit/chalmersit-rails#355]
On the front page on in post details when i zoom the post titles get enlarged like expected. But sometimes a word gets cut off in the middle without a "-" bore the new line.

See it in action: https://chalmers.it/posts/973-ta-hem-era-agodelar-innan-rustveckan

I have 1080p screen :)

**Comment by Portals** [comment]
Could you please provide a screenshot?

**Comment by ericlp** [comment]
![screenshot from 2018-05-22 16-27-51](https://user-images.githubusercontent.com/31534278/40368926-1f58a720-5ddd-11e8-99c6-942780cb4e62.png)

**Comment by Kalior** [comment]
Seems to work as expected on chromium at least, but I experience the same issue on firefox.  `word-break: keep-all;` fixes it I believe.
