### ISSUE TITLE
Remove 'parent' link in pages

### ISSUE THREAD

**Issue by Kalior** [cthit/chalmersit-rails#369]
I don't like it and I don't find it necessary.  What does current digit say about removing it? 

See bottom left corner in e.g.:
![2018-10-14-001037_2193x1278_scrot](https://user-images.githubusercontent.com/2412457/46910495-aef84780-cf45-11e8-926d-683e11885c6c.png)

**Comment by Portals** [comment]
I am for removing it. What do you think @elias-sundqvist ?
