### ISSUE TITLE
Pages should have nested route from parents

### ISSUE THREAD

**Issue by lindskogen** [cthit/chalmersit-rails#37]
Preferably with arbitrary depth.

Example: `/sektionen/historia` where `sektionen` is parent page of `historia`.

Resource: http://railscasts.com/episodes/46-catch-all-route

**Comment by Ndushi** [comment]
Fallback to parent page

**Comment by Cannonbait** [comment]
This is done, but works bork. / is url encoded and I'm not sure on how to fix it.

See https://github.com/rails/rails/issues/16058§

**Comment by Criticalstone** [comment]
Also there seems to an issue when creating pages, I think the problem lies within the pages controller

**Comment by Criticalstone** [comment]
Fixed by d416b14
