### ISSUE TITLE
Contactform not working

### ISSUE THREAD

**Issue by Baloo1** [cthit/chalmersit-rails#380]
The [contact page](https://chalmers.it/contact) does not seem to be working. Trying to message styrIT, SAMO and possibly others dont work. The form itself does not indicate any problems but the messages does not reach the inbox of anyone. It has been like this for awhile but not sure how long.

Found #358 and cant tell if they are related.

@williamleven had a theory

**Comment by Portals** [comment]
Yeah it's related but actually didn't solve the issue.

**Comment by williamleven** [comment]
Might be more problems tho...

The old method of sending emails is probably not valid since we changed to the new gsuite account.

**Comment by williamleven** [comment]
https://github.com/cthit/gotify can be used to send mails with a simple post request now

**Comment by NeonNeon** [comment]
Did 42f9d8827cbb6f2c498473ef1728f70982ffc3a7 fix this? I can't tell. Tried to send myself emails but did not work

**Comment by Hoidi** [comment]
No sorry it's not live yet ☹️

**Comment by NeonNeon** [comment]
I mean: does this work in the master branch? I tried to verify it but couldnt
