### ISSUE TITLE
Make "Studiesocialhjälp" information availble on website

### ISSUE THREAD

**Issue by Baloo1** [cthit/chalmersit-rails#381]
It would be great for social and work enviroment to highlight all the support functions Chalmers offers for students on Chalmers.it 

A simple but good solution could be to copy [Data](https://dtek.se/) and their rightmost icon "Studiesocialhjälp"

**Comment by NeonNeon** [comment]
Finns det ett mostvarande dokument för IT-sektionen? Eller kan man ha en länk till någonstans på kårens hemsida?
Data verkar ju visa en pdf som de har lokalt på sin hemsida
