### ISSUE TITLE
Anounce newspost in the #it channel on irc.chalmers.it

### ISSUE THREAD

**Issue by oed** [cthit/chalmersit-rails#42]
Using http is irksome. When a news item is posted on the website there should be a script that post it in the #it channel. 
This can be implemented with a simple script that connects to the irc network and post directly to that channel. 
Removing the channel flag n it's possible to make the script post without joining the channel.

**Comment by Dr-Horv** [comment]
That's a neat idea, I approve!

**Comment by Vilddjur** [comment]
closed by a83350b6b5975201de55c7474b55a187aec4db14
