### ISSUE TITLE
Users need a way to upload profile pictures and we need a way to store them.

### ISSUE THREAD

**Issue by NeonNeon** [cthit/chalmersit-rails#45]
Can we store pictures directly into the database? Whenever a user uploads a new picture there is an update in the Users table?

**Comment by NeonNeon** [comment]
As far as I understand there are two different ways to do this.

1. We let every user in our database (LDAP?) have a profile picture as an attribute. Then the rails server at mustafa would have to query the mysql server at naboo?
2. We let User.rb have a profile picture connected to it and let the rails server at mustafa do what it does best, the downside is if we want another service to use the pictures option 1 is better.

Disclaimer: I have no idea what I'm doing so feedback please

**Comment by Kalior** [comment]
@oskar367 is it now possible to link this missing image to the new accounts site where the user has a profile picture?

**Comment by Kalior** [comment]
according to @oskar367 this is fixed by the account system.

**Comment by oskar367** [comment]
solved as of [this](https://github.com/cthit/chalmersit-account-rails/commit/b10dc4b57c826eeddad70d71e4492fb5c3e1b130)

**Comment by lindskogen** [comment]
gj! :+1:
