### ISSUE TITLE
Einstein lunch parsing is not correct

### ISSUE THREAD

**Issue by Kalior** [cthit/chalmersit-rails#46]
The parsing seems to return an array with a hash in it which does not work in the same manner as the other lunches. 
This needs to be fixed either by handling it in the front end or changing the parser.

**Comment by Edholm** [comment]
I think digIT (or didIT) should [contact](mailto:info@butlercatering.se) them and ask if they could add an RSS feed. 

If we mention that we would like to add their menu to our site, maybe the would consider it.

**Comment by Kalior** [comment]
Good idea!
