### ISSUE TITLE
Company site in the header

### ISSUE THREAD

**Issue by Kalior** [cthit/chalmersit-rails#56]
To mimic the as-is on chalmers.it there should be a company site with information from armIT that should be static?

**Comment by Criticalstone** [comment]
They are working on a new website for company contacts. Could just be a link to that site?

**Comment by Kalior** [comment]
I think we should take to ArmIT and see what they want in that case. A link to that site might be appropriate in that case.

**Comment by Kalior** [comment]
@Criticalstone can you ask ArmIT how they want this to be when the new chalmers.it launches?

**Comment by Vilddjur** [comment]
Closed by #64

**Comment by Kalior** [comment]
I don't think this issue is what you think it is. The Buisness partner cards are great, but the link to ArmIT's site in the header is still missing. 
![2016-05-19-101531_1273x117_scrot](https://cloud.githubusercontent.com/assets/2412457/15386948/c87671c2-1daa-11e6-89e7-70701ea65ccf.png)
![2016-05-19-101519_1095x121_scrot](https://cloud.githubusercontent.com/assets/2412457/15386947/c87540fe-1daa-11e6-8320-1bcf644830ac.png)
As you can see "Företag" is missing.

However, we can just tell ArmIT how to add this themselves, and walk them through how.

**Comment by Vilddjur** [comment]
I think it might just be better to show ArmIT how to do it since that will teach them how to maintain it.

**Comment by Vilddjur** [comment]
closed by 3f5fa7a363403fdeab1e8135dd3d68abfcda0981
