### ISSUE TITLE
Remove Courses page

### ISSUE THREAD

**Issue by Kalior** [cthit/chalmersit-rails#59]
PL (that is, the people in charge of the IT programme) feels that the `Courses` page is redundant and can lead to confusion if not kept up to date. They feel that rather than someone here trying to keep the page up to date that we link to where the information about courses can be found, that is [here](https://student.portal.chalmers.se/sv/chalmersstudier/programinformation/Sidor/SokProgramutbudet.aspx?program_id=1231&parsergrp=1). Thoughts?

**Comment by hjorthjort** [comment]
I agree. The page hasn't really been kept up to date. Assuming there is no possibility to extract this directly from official sources (is there an api of some kind, that would be super), we better just link to the sources.

Although, of course, it's nice to not send people off to another page for interaction design purposes, it might be a better solution than manually updating that page over and over.

**Comment by bark** [comment]
It worked good for a long time when it was wiki style. But it got changed, To only SnIT have edit privileges to keep it up to date, And it completely stopped working. so if you keep it change it back to wiki style that all can update.

**Comment by Dr-Horv** [comment]
While the page being out of date is quite bad. The page @Kalior linked to doesn't have the course pages listed, only their student portal page which might or might not have the actual course page link.

I did like how it worked on the old version of chalmers.it. Back then it was wiki-like. So anyone who was logged in could edit and update it. If you found a course which was not up to date, you simply edited it.

**Comment by Kalior** [comment]
I believe the current implementation on chalmers.it rails is such that everyone that is signed in can change the courses. I am, however, not confident that it will be kept up to date regardless. I do suppose we can try it though, and if it doesn't work half a year after deployment we can change it? 

An api would of course be the best solution, but I don't think we can expect there to be one any time soon. 

I agree that course home pages is an issue with linking to studentportalen.

**Comment by Kalior** [comment]
With the recent introduction of an IT wiki, do we still feel the need to have a courses page on Chalmers.it? I feel like it would be better to have wikit.chalmers.it contain the wiki-like courses page of the old chalmers.it and either link to that or to studentportalen on chalmers.it. Alternatively remove the courses feature completely. Any other thoughts on this?

**Comment by NeonNeon** [comment]
I agree, we could have a link to the IT wiki page "kurser".

**Comment by Dr-Horv** [comment]
I'm not sure. As it is now we've taken it upon it as snITs duty to update
the course page befire every study period starts on Chalmers.it and until
it-wiki has gotten more adaption im not sure it is a wise move to move it.
Although I'm unsure if anyone uses the course page

**Comment by NeonNeon** [comment]
https://wikit.chalmers.it/wiki/Kurser
Check it out yo

**Comment by Kalior** [comment]
@NeonNeon That looks great! :couch_and_lamp: I think the only missing thing, really (besides adding in more non-compulsory courses and the masters programmes, although that will come in time I'm sure) is a link to the program plan (which I coincidentally just added :D)-

@Dr-Horv Yeah, I agree that it's great if the information is available, and it is fantastic that you keep the page up to date. How do you feel about linking to the wiki from chalmers.it? I recognise that this makes the information slightly less accessible. I feel like the people using the courses page is people who are curious about upcoming courses and when trying to figure out when you took what course, and occasionally people looking for course home pages. But I believe the latter use case is mostly replaced by a bookmark to that page.

**Comment by Vilddjur** [comment]
We might be able to open the "Kurser" page to the public using the [PageSecurity](https://www.mediawiki.org/wiki/Extension:PageSecurity) extension for mediawiki.

**Comment by Vilddjur** [comment]
closed by dafb41f29430828d23d5c7349c3000df1fdff113
