### ISSUE TITLE
"Signed in" confirmation alert is hidden behind the logo

### ISSUE THREAD

**Issue by jesperlindstrom** [cthit/chalmersit-rails#60]
<img width="1383" alt="skarmavbild 2016-05-03 kl 18 21 40" src="https://cloud.githubusercontent.com/assets/1730738/14990261/114386c0-115c-11e6-884c-4e14bc5be002.png">

"Signed in" confirmation alert is hidden behind the logo.

**Comment by Vilddjur** [comment]
![index_alert_box](https://cloud.githubusercontent.com/assets/5731291/15571138/91fdc782-2339-11e6-8054-165a05c3f146.png)
What about this? Solves it for large screens at least

**Comment by Vilddjur** [comment]
closed by fcd926e8f766b8e8babeb55d0c3ade3c6eb4abe6
