### ISSUE TITLE
Tools dropdown is outside of the screen

### ISSUE THREAD

**Issue by jesperlindstrom** [cthit/chalmersit-rails#61]
<img width="740" alt="skarmavbild 2016-05-03 kl 18 21 32" src="https://cloud.githubusercontent.com/assets/1730738/14990310/5062af0c-115c-11e6-8407-c7fb53da2976.png">

Tools dropdown is outside of the screen and is behaving weirdly

**Comment by Vilddjur** [comment]
Closed by bcf7821c74d9afd53def88d0bccf1c900243e97a
