### ISSUE TITLE
Removing attached file results in 404

### ISSUE THREAD

**Issue by kirayatail** [cthit/chalmersit-rails#67]
When posting news

**Comment by Vilddjur** [comment]
From what I could understand from @Trivoc he was redirected to the post after the error, he could then see the documents he previously added (which is good for when editing posts) and he then tried to remove the document when he got a 404. This is intended in the sense that if you get an error when posting the system never uploads the users documents. But of course it is misleading as it is now

**Comment by Vilddjur** [comment]
closed by deb9a16aa2b708b2cff3c52617c03ee4fd0b20ac
