### ISSUE TITLE
Editing settings should not require password

### ISSUE THREAD

**Issue by kirayatail** [cthit/chalmersit-rails#68]
Tried to set default language, and was prompted that my password was too short.

Changing non-critical settings should not require a password change.

<img width="843" alt="skarmavbild 2016-05-20 kl 11 01 27" src="https://cloud.githubusercontent.com/assets/1055844/15422791/766065ac-1e7a-11e6-97b8-0c0deafe5583.png">

**Comment by lindskogen** [comment]
Please move issue to chalmersit-account-rails
