### ISSUE TITLE
Linsen lunch feed is not parsing for english locale

### ISSUE THREAD

**Issue by Vilddjur** [cthit/chalmersit-rails#70]
I think they stopped updating the english counterpart in their lunch feed? 
http://intern.chalmerskonferens.se/view/restaurant/linsen/RSS%20Feed.rss?today=true&locale=sv
http://intern.chalmerskonferens.se/view/restaurant/linsen/RSS%20Feed.rss?today=true&locale=en

**Comment by lindskogen** [comment]
Isn't this because of summer time?

**Comment by Kalior** [comment]
How is it related to summer time?

**Comment by lindskogen** [comment]
The restaurants will not be open during the summer, and people get lazy

**Comment by kirayatail** [comment]
@Kalior actual season, not Daylight Savings Time.

Reasonable to fall back on swedish content if english isn't available? Content before culture!

**Comment by Kalior** [comment]
Ah right. Could be reasonable to fall back on the swedish lunch feed. Or try to perform a hack translation from the swedish lunch feed? :dancer:

**Comment by kirayatail** [comment]
Google translate does a decent job with a few test cases. Do they have an API?

**Comment by Dr-Horv** [comment]
Has anyone actually tried to communicate with them? Ask why it isn't updated?
