### ISSUE TITLE
Asset pipeline looking in wrong directory?

### ISSUE THREAD

**Issue by Vilddjur** [cthit/chalmersit-rails#73]
So I just casually wanted to check out beta.chalmers.it and was greeted with an error. Turns out that it seems like rails asset pipeline looks by default in uploads/current_year/current_month/image.png which gave me a 404. I know that the images are saved that way but when we request the sources of the images it looks in the latest months directory. I "fixed" it now by copying an image that was throwing the error on the server, this was just to make sure that that was the issue here.

**Comment by lindskogen** [comment]
The asset pipeline has nothing to do with files uploaded with carrierwave, what is actually happening?

**Comment by Vilddjur** [comment]
This might just have been a bad version of the software as I haven't seen this issue anymore and it disappeared when I updated
