### ISSUE TITLE
Can't remove profile picture

### ISSUE THREAD

**Issue by lindbergan** [cthit/chalmersit-rails#75]
Tried to remove my profile picture to update to something more suiting. This happens:

If you can't see the gif below, I click "remove" and the website refreshes yet nothing has changed. 

![Unclear gif on what's happening](http://g.recordit.co/5D8Fr0QOfg.gif)

**Comment by Kalior** [comment]
I believe this issue concerns [chalmersit-wordpress](https://github.com/cthit/chalmersit-wordpress).
