### ISSUE TITLE
Remove Twitter widget

### ISSUE THREAD

**Issue by jesperlindstrom** [cthit/chalmersit-rails#78]
<img width="340" alt="skarmavbild 2016-08-30 kl 19 49 10" src="https://cloud.githubusercontent.com/assets/1730738/18100356/e4fb5e7a-6eea-11e6-8c04-78e1dae180fb.png">

I suggest we hide/remove the Twitter widget for now, as we don't have a public official Twitter anymore. The alternative, FlashIT, also isn't active here, with the most recent post being 2013.

**Comment by lindskogen** [comment]
resonable
