### ISSUE TITLE
Committees model

### ISSUE THREAD

**Issue by lindskogen** [cthit/chalmersit-rails#8]
Backed with LDAP

**Comment by Cannonbait** [comment]
There is a description but there is lack of possibility to have an image. We should also link up this to automatically list and show images of all current committée members.

**Comment by Kalior** [comment]
@Cannonbait Is this done?

**Comment by Vilddjur** [comment]
@Kalior Is this done?

**Comment by Kalior** [comment]
heh, nope. The thought was, if I remember correctly, to store the data in accounts and then get that information and display it on each Committee

**Comment by Vilddjur** [comment]
Alright so we still need a way to store/show an image for each commitee?

**Comment by Kalior** [comment]
I believe so

**Comment by Vilddjur** [comment]
So what seems to be left for this is pretty much to allow markdown. This should be tied to account though.

**Comment by Vilddjur** [comment]
I suppose we are fine for 1.0 if we just can get the markdown working

**Comment by Vilddjur** [comment]
seems like it already has [markdown](https://github.com/cthit/chalmersit-rails/blob/develop/app/views/committees/show.html.erb#L11)
No preview though

**Comment by Vilddjur** [comment]
closed by 9a7db7c5e77e55dfc508ee517d023972a0a8de42
