### ISSUE TITLE
Event calendar is incorrect

### ISSUE THREAD

**Issue by Vilddjur** [cthit/chalmersit-rails#85]
The event calendar om [beta.chalmers.it](https://beta.chalmers.it/) doesn't have all the events that are in [chalmers.it](https://chalmers.it/)'s calendar. Is this because of events that are only registered in the wordpress calendar and not in the google one? I looked around and it doesn't seem to be because of cacheing.

**Comment by lindskogen** [comment]
The calendar for beta.chalmers.it displays events from a google calendar url:
https://github.com/cthit/chalmersit-rails/blob/develop/config/configurable.yml#L49

**Comment by Vilddjur** [comment]
Yes and it is the same calendar in the wordpress version but when i tried to look it through in order to check all the events some where missing. For instance the drawit event "[DrawIT spelar brädspel](https://calendar.google.com/calendar/render?eid=ZHA5YjBwajhtY2c3M3VycGhhcWtmZ29lZW9fMjAxNjA5MjhUMTUwMDAwWiBhNTVpcGQzbzQ5bjA1Y2QyZWVicW84NTRxc0Bn&ctz=Europe/Stockholm&sf=true&output=xml#eventpage_6)" on 28/9 exists only in the calendar on chalmers.it and not in beta.chalmers.it.

**Comment by Vilddjur** [comment]
I should mentiond that I didn't look in the calendar but in the basic.ics file that you recieve through that adress

**Comment by Kalior** [comment]
Might be an issue with repeating events, since that is what drawITs event is but none else

**Comment by lindskogen** [comment]
Probably is, yeah
