### ISSUE TITLE
Posting at beta.chalmers.it

### ISSUE THREAD

**Issue by SamuelHakansson** [cthit/chalmersit-rails#87]
- Unclear how English/Swedish tabs are supposed to be used.
- Problem uploading file, uploaded a .png file which was working on chalmers.it, beta.chalmers.it interpreted it as not "jpeg/png...".
- When trying with the same picture later, it pasted it as code into the body and deleted whatever was there before.
- Were unable to post (to click "Create news post"), no action when clicking. (Should've taken a screen shot). Would be nice with error messages if posting is unavailable.
- Unclear what "Sticky" means.
- Would be nice to use "swedish time" and not AM/PM. 
- When conversion from 15 to 03, it would be better to also change from AM to PM. If AM/PM is kept.

**Comment by Vilddjur** [comment]
The problem with AM/PM on time inputs is based on the browser according to some guy on stackoverflow. I tested on my computer with Chromium and Google chrome both gave 24hr input, however when i tried with firefox it didn't validate the number i.e it looked like this ![firefox time input](https://i.gyazo.com/48a9e4c60f279a1ffc084988328a270e.png)
So I don't think there is anything we can do about that at the moment.

**Comment by Vilddjur** [comment]
And when I tried the image input was not an issue but it might be a problem with the support for your browser. What browser were you using and could you send the image you were unable to upload?

**Comment by hjorthjort** [comment]
Split this into 7 distinct issues?

**Comment by hjorthjort** [comment]
This has been split into distinct issues: #89, #90, and #91. Closing this one.
