### ISSUE TITLE
Pages model

### ISSUE THREAD

**Issue by lindskogen** [cthit/chalmersit-rails#9]
Hierarchical model for a generic `Page`, with parent and subpages. Maybe limit depth to just one level of children.

**Comment by Meddan** [comment]
Should not be able to set itself as parent when editing.

**Comment by Cannonbait** [comment]
Are we done with this? URL works as it should, I believe we are finished. @lindskogen?

**Comment by Criticalstone** [comment]
solved by commit d416b14
