### ISSUE TITLE
Problem uploading file with new post

### ISSUE THREAD

**Issue by hjorthjort** [cthit/chalmersit-rails#90]
- Problem uploading file, uploaded a .png file which was working on chalmers.it, beta.chalmers.it interpreted it as not "jpeg/png...".
- When trying with the same picture later, it pasted it as code into the body and deleted whatever was there before.

_Split from #87_

**Comment by Kerp1** [comment]
I tried to reproduce this but it seemed to work for me, the correct markup to display the picture was appended to the post at least.

**Comment by Vilddjur** [comment]
Im setting the label to low for now.

**Comment by Vilddjur** [comment]
second part fixed asof 69a50e9c90ec262c739aab67212f0a54879ea48b

**Comment by Vilddjur** [comment]
I am closing this since this problem seems to not be reproducible
